spring:
  application:
    name: ${SPRING_APP_NAME:springsecurity1}
  data:
    mongodb:
      uri: mongodb://localhost:27017/SecurityAudit

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}